In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from tqdm import tqdm
from itertools import product
import numpy as np
from src.EModel import EModel
from src.EDistribution import EDistribution
from src.get_xy_sample import get_xy_sample
from src.config import RNG, RANDOM_STATE, GLOBAL_PATH_TO_REPO
from src.train_and_evaluate_all_models import train_and_evaluate_all_models
from src.EDistribution import EDistribution

In [56]:
def f(x, y):
    return np.sin(np.sqrt(x ** 2 + y ** 2))

x = np.linspace(-1, 1, 11)
y = np.linspace(-1, 1, 11)

X, Y = np.meshgrid(x, y)
Z = f(X, Y)
Z.shape

(11, 11)

In [63]:
Z[0]

array([0.98776595, 0.95819483, 0.91925759, 0.88055548, 0.85200537,
       0.84147098, 0.85200537, 0.88055548, 0.91925759, 0.95819483,
       0.98776595])

In [60]:
X[10]

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [50]:
x = np.linspace(-1, 1, 11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [48]:
N = 60
M = 680
beta = np.ones(N)
X, y = get_xy_sample(distribution_type=EDistribution.normal, beta=beta, sample_size=10_000, rho=0.01)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=RANDOM_STATE, train_size=M)
score_dict = train_and_evaluate_all_models(X_train=X_train, X_test=X_test, y_test=y_test, y_train=y_train, n_components=2)
score_dict

{'R2': {'linreg': 0.9887753511621339,
  'pcr': 0.7608624424891614,
  'pls': 0.9847026433694994},
 'MSE': {'linreg': 1.0789586440773862,
  'pcr': 22.986869213177492,
  'pls': 1.4704437890594086}}